# Generated by Django 5.1.7 on 2025-03-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restables',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_num', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='available', max_length=10)),
            ],
            options={
                'db_table': 'restables',
            },
        ),
    ]
