# Generated by Django 5.1.7 on 2025-03-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=255)),
                ('dish_price', models.IntegerField()),
                ('dish_img', models.CharField(max_length=255)),
            ],
        ),
    ]
