# Generated by Django 5.1.7 on 2025-03-23 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='dish_img',
            new_name='type',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
